# Generated by Django 2.2.16 on 2022-02-16 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20220216_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='user',
        ),
        migrations.AddField(
            model_name='userfollow',
            name='user',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
