# Generated by Django 2.2.16 on 2022-02-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220216_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
